export enum Grade {
    a = "A",
    a_minus = "A-",
    b_plus = "B+",
    b = "B",
    b_minus = "B-",
    c_plus = "C+",
    c = "C",
    c_minus = "C-",
    d_plus = "D+",
    d = "D",
    f = "F",
    i = "I",
    w = "W",
    q = "Q",
    s = "S",
    u = "U",
    na = "NA",
    empty = ""
}
